Update changelog for release
mihaimaruseac/hindent pull request #744
Opened 2023-05-17 13:28 UTC by mihaimaruseac

### Description of the PR

### Checklist

- [ ] Add a changelog if necessary. See https://keepachangelog.com/ for how to write it.
- [ ] Add tests in [TESTS.md](/TESTS.md) if possible.

2023-05-17 13:33 UTC, toku-sa-n commented
I think the next version should be 6.1.0 as there are breaking changes (like `reformat`'s signature change). After that version, we should be able to increment the patch number as long as we don't modify exposed contents in the `HIndent` module.

2023-05-17 13:37 UTC, mihaimaruseac commented
Right, thanks for noticing. Updated

2023-05-17 13:41 UTC, toku-sa-n requested changes

2023-05-17 13:45 UTC, mihaimaruseac commented on CHANGELOG.md
Thanks. Too early for me, missed it

2023-05-17 13:54 UTC, mihaimaruseac commented
Updated `package.yaml`, the `.cabal` file was updated before.

2023-05-17 13:56 UTC, toku-sa-n approved these changes
Thank you!

2023-05-17 14:04 UTC, merged

2023-05-17 23:42 UTC, toku-sa-n commented
Thanks for the release! Did you update the Hackage one?

2023-05-17 23:45 UTC, mihaimaruseac commented
No, I had to leave for work. Just got home and will do the upload now.

2023-05-17 23:51 UTC, mihaimaruseac commented
Now it should be at https://hackage.haskell.org/package/hindent-6.1.0 (documentation I think will be updated shortly, it's weird we only have the top level module only)

2023-05-18 00:02 UTC, toku-sa-n commented
Thank you!

> it's weird we only have the top level module only

It's expected as we did in #729.

2023-05-18 00:03 UTC, mihaimaruseac commented
Oh, my bad, forgot about it.

Nice.